// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvbcSIFg7WFnC6Lyi-G5Y1M2DRfUCAkVg',
    appId: '1:377322616450:web:14349e2636698a2fc9e69b',
    messagingSenderId: '377322616450',
    projectId: 'phoria-application',
    authDomain: 'phoria-application.firebaseapp.com',
    storageBucket: 'phoria-application.firebasestorage.app',
    measurementId: 'G-L6YP46R6HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxVZlWyjb0xOBSWvJuzOIZDMYEGlBnWQ',
    appId: '1:377322616450:android:2d0c12dfaa626d96c9e69b',
    messagingSenderId: '377322616450',
    projectId: 'phoria-application',
    storageBucket: 'phoria-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvKG5nWbWQ3by2yU8dV3I8P4MiYSWcBqg',
    appId: '1:377322616450:ios:160c8e3cf0eeae79c9e69b',
    messagingSenderId: '377322616450',
    projectId: 'phoria-application',
    storageBucket: 'phoria-application.firebasestorage.app',
    iosBundleId: 'com.example.phoriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvKG5nWbWQ3by2yU8dV3I8P4MiYSWcBqg',
    appId: '1:377322616450:ios:160c8e3cf0eeae79c9e69b',
    messagingSenderId: '377322616450',
    projectId: 'phoria-application',
    storageBucket: 'phoria-application.firebasestorage.app',
    iosBundleId: 'com.example.phoriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvbcSIFg7WFnC6Lyi-G5Y1M2DRfUCAkVg',
    appId: '1:377322616450:web:912bb7b29294ebcac9e69b',
    messagingSenderId: '377322616450',
    projectId: 'phoria-application',
    authDomain: 'phoria-application.firebaseapp.com',
    storageBucket: 'phoria-application.firebasestorage.app',
    measurementId: 'G-RHXZ7X8D23',
  );
}
